name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: cafxx/static_asset_server:latest
        file: Dockerfile.builder
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
  build-demo:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy the example assets to the webroot
      run: cp assets/source/* webroot/
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image for the asset server with the example assets
      run: docker build --tag registry.heroku.com/cafxx-static-asset-server-demo/web --file Dockerfile .
    - name: Login to Heroku Container registry
      if: ${{ github.ref == 'refs/heads/main' }}
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login 
    - name: Push the Docker image
      if: ${{ github.ref == 'refs/heads/main' }}
      run: docker push registry.heroku.com/cafxx-static-asset-server-demo/web
    - name: Deploy server
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release -a cafxx-static-asset-server-demo web
